### ISSUE TITLE
Error occurred on "docker-compose up"

### ISSUE THREAD

**Issue by webos21** [IoTKETI/Mobius_Docker#1]
jocheolmin@jocheolmin-ui-MacBook-Pro Mobius_Docker % docker-compose up
Pulling db (mysql:5.7)...
5.7: Pulling from library/mysql
8f91359f1fff: Pull complete
6bbb1c853362: Pull complete
e6e554c0af6f: Pull complete
f391c1a77330: Pull complete
414a8a88eabc: Pull complete
fee78658f4dd: Pull complete
9568f6bff01b: Pull complete
b348bc63b89d: Pull complete
864b3bbd0929: Pull complete
db5f27a8464a: Pull complete
25e330fc30b8: Pull complete
Digest: sha256:759e6019aefb5d5a4e24920b223d85ed1ef9e3e66dd457ff469370dd1e050180
Status: Downloaded newer image for mysql:5.7
Pulling node (node:7.6)...
7.6: Pulling from library/node
693502eb7dfb: Pull complete
081cd4bfd521: Pull complete
5d2dc01312f3: Pull complete
54a5f7da9a4f: Pull complete
f6ebc0704397: Pull complete
cd487f72ac9f: Pull complete
d3e88bf53e70: Pull complete
88dbf525e469: Pull complete
Digest: sha256:34d21bab49105c1ab384e50432aa6ebd6dac69c2637378e7ecb6f40cda97118b
Status: Downloaded newer image for node:7.6
Pulling mqtt (eclipse-mosquitto:latest)...
latest: Pulling from library/eclipse-mosquitto
c87736221ed0: Pull complete
2915d3f9d322: Pull complete
79704471e17d: Pull complete
Digest: sha256:d6d255052b779cdc704418710d30638bf387e6d8e4e707feb6a7a580e184b748
Status: Downloaded newer image for eclipse-mosquitto:latest
Creating mobius_docker_db_1 ... done
Creating mobius_docker_mqtt_1 ... done
Creating mobius_docker_node_1 ... done
Attaching to mobius_docker_db_1, mobius_docker_mqtt_1, mobius_docker_node_1
db_1    | 2019-10-17 04:12:10+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.
mqtt_1  | 1571285561: mosquitto version 1.6.7 starting
mqtt_1  | 1571285561: Config loaded from /mosquitto/config/mosquitto.conf.
mqtt_1  | 1571285561: Opening ipv4 listen socket on port 1883.
mqtt_1  | 1571285561: Opening ipv6 listen socket on port 1883.
db_1    | 2019-10-17 04:12:10+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1    | 2019-10-17 04:12:10+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.
db_1    | 2019-10-17 04:12:10+00:00 [Note] [Entrypoint]: Initializing database files
db_1    | 2019-10-17T04:12:10.455816Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1    | 2019-10-17T04:12:10.955041Z 0 [Warning] InnoDB: New log files created, LSN=45790
db_1    | 2019-10-17T04:12:11.006250Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
db_1    | 2019-10-17T04:12:11.014274Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 4aac4ca4-f094-11e9-87c5-025000000001.
db_1    | 2019-10-17T04:12:11.015845Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
db_1    | 2019-10-17T04:12:11.305426Z 0 [Warning] CA certificate ca.pem is self signed.
db_1    | 2019-10-17T04:12:11.630988Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
db_1    | 2019-10-17 04:12:14+00:00 [Note] [Entrypoint]: Database files initialized
db_1    | 2019-10-17 04:12:14+00:00 [Note] [Entrypoint]: Starting temporary server
db_1    | 2019-10-17 04:12:14+00:00 [Note] [Entrypoint]: Waiting for server startup
db_1    | 2019-10-17T04:12:14.206573Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1    | 2019-10-17T04:12:14.207901Z 0 [Note] mysqld (mysqld 5.7.28) starting as process 82 ...
db_1    | 2019-10-17T04:12:14.211440Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1    | 2019-10-17T04:12:14.211520Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1    | 2019-10-17T04:12:14.211542Z 0 [Note] InnoDB: Uses event mutexes
db_1    | 2019-10-17T04:12:14.211570Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1    | 2019-10-17T04:12:14.211598Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1    | 2019-10-17T04:12:14.211688Z 0 [Note] InnoDB: Using Linux native AIO
db_1    | 2019-10-17T04:12:14.212177Z 0 [Note] InnoDB: Number of pools: 1
db_1    | 2019-10-17T04:12:14.212492Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1    | 2019-10-17T04:12:14.214237Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1    | 2019-10-17T04:12:14.223271Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1    | 2019-10-17T04:12:14.225494Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1    | 2019-10-17T04:12:14.239015Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1    | 2019-10-17T04:12:14.249765Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1    | 2019-10-17T04:12:14.249920Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1    | 2019-10-17T04:12:14.294680Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1    | 2019-10-17T04:12:14.296204Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1    | 2019-10-17T04:12:14.296330Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1    | 2019-10-17T04:12:14.297033Z 0 [Note] InnoDB: Waiting for purge to start
db_1    | 2019-10-17T04:12:14.347959Z 0 [Note] InnoDB: 5.7.28 started; log sequence number 2628227
db_1    | 2019-10-17T04:12:14.348509Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1    | 2019-10-17T04:12:14.349799Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1    | 2019-10-17T04:12:14.351915Z 0 [Note] InnoDB: Buffer pool(s) load completed at 191017  4:12:14
db_1    | 2019-10-17T04:12:14.357722Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1    | 2019-10-17T04:12:14.357808Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
db_1    | 2019-10-17T04:12:14.358743Z 0 [Warning] CA certificate ca.pem is self signed.
db_1    | 2019-10-17T04:12:14.358843Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
db_1    | 2019-10-17T04:12:14.361026Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1    | 2019-10-17T04:12:14.368516Z 0 [Note] Event Scheduler: Loaded 0 events
db_1    | 2019-10-17T04:12:14.368977Z 0 [Note] mysqld: ready for connections.
db_1    | Version: '5.7.28'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
db_1    | 2019-10-17 04:12:15+00:00 [Note] [Entrypoint]: Temporary server started.
db_1    | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
db_1    | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
db_1    | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
db_1    | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
db_1    | 2019-10-17 04:12:17+00:00 [Note] [Entrypoint]: Creating database mobiusdb
db_1    | 
db_1    | 2019-10-17 04:12:17+00:00 [Note] [Entrypoint]: Stopping temporary server
db_1    | 2019-10-17T04:12:18.009331Z 0 [Note] Giving 0 client threads a chance to die gracefully
db_1    | 2019-10-17T04:12:18.009396Z 0 [Note] Shutting down slave threads
db_1    | 2019-10-17T04:12:18.009432Z 0 [Note] Forcefully disconnecting 0 remaining clients
db_1    | 2019-10-17T04:12:18.009467Z 0 [Note] Event Scheduler: Purging the queue. 0 events
db_1    | 2019-10-17T04:12:18.009593Z 0 [Note] Binlog end
db_1    | 2019-10-17T04:12:18.010348Z 0 [Note] Shutting down plugin 'ngram'
db_1    | 2019-10-17T04:12:18.010427Z 0 [Note] Shutting down plugin 'partition'
db_1    | 2019-10-17T04:12:18.010447Z 0 [Note] Shutting down plugin 'BLACKHOLE'
db_1    | 2019-10-17T04:12:18.010516Z 0 [Note] Shutting down plugin 'ARCHIVE'
db_1    | 2019-10-17T04:12:18.010614Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
db_1    | 2019-10-17T04:12:18.010689Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
db_1    | 2019-10-17T04:12:18.010728Z 0 [Note] Shutting down plugin 'MyISAM'
db_1    | 2019-10-17T04:12:18.010760Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
db_1    | 2019-10-17T04:12:18.010795Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
db_1    | 2019-10-17T04:12:18.010887Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
db_1    | 2019-10-17T04:12:18.010907Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
db_1    | 2019-10-17T04:12:18.010995Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
db_1    | 2019-10-17T04:12:18.011025Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
db_1    | 2019-10-17T04:12:18.011058Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
db_1    | 2019-10-17T04:12:18.011157Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
db_1    | 2019-10-17T04:12:18.011193Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
db_1    | 2019-10-17T04:12:18.011215Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
db_1    | 2019-10-17T04:12:18.011304Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
db_1    | 2019-10-17T04:12:18.011378Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
db_1    | 2019-10-17T04:12:18.011421Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
db_1    | 2019-10-17T04:12:18.011449Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
db_1    | 2019-10-17T04:12:18.011518Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
db_1    | 2019-10-17T04:12:18.011574Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
db_1    | 2019-10-17T04:12:18.011653Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
db_1    | 2019-10-17T04:12:18.011701Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
db_1    | 2019-10-17T04:12:18.011728Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
db_1    | 2019-10-17T04:12:18.011817Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
db_1    | 2019-10-17T04:12:18.011835Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
db_1    | 2019-10-17T04:12:18.011922Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
db_1    | 2019-10-17T04:12:18.011962Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
db_1    | 2019-10-17T04:12:18.012011Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
db_1    | 2019-10-17T04:12:18.012042Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
db_1    | 2019-10-17T04:12:18.012061Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
db_1    | 2019-10-17T04:12:18.012100Z 0 [Note] Shutting down plugin 'INNODB_CMP'
db_1    | 2019-10-17T04:12:18.012124Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
db_1    | 2019-10-17T04:12:18.012206Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
db_1    | 2019-10-17T04:12:18.012267Z 0 [Note] Shutting down plugin 'INNODB_TRX'
db_1    | 2019-10-17T04:12:18.012304Z 0 [Note] Shutting down plugin 'InnoDB'
db_1    | 2019-10-17T04:12:18.012566Z 0 [Note] InnoDB: FTS optimize thread exiting.
db_1    | 2019-10-17T04:12:18.013270Z 0 [Note] InnoDB: Starting shutdown...
db_1    | 2019-10-17T04:12:18.116348Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
db_1    | 2019-10-17T04:12:18.117051Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 191017  4:12:18
db_1    | 2019-10-17T04:12:19.237218Z 0 [Note] InnoDB: Shutdown completed; log sequence number 12436822
db_1    | 2019-10-17T04:12:19.240756Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1    | 2019-10-17T04:12:19.240854Z 0 [Note] Shutting down plugin 'MEMORY'
db_1    | 2019-10-17T04:12:19.240879Z 0 [Note] Shutting down plugin 'CSV'
db_1    | 2019-10-17T04:12:19.240898Z 0 [Note] Shutting down plugin 'sha256_password'
db_1    | 2019-10-17T04:12:19.240964Z 0 [Note] Shutting down plugin 'mysql_native_password'
db_1    | 2019-10-17T04:12:19.241305Z 0 [Note] Shutting down plugin 'binlog'
db_1    | 2019-10-17T04:12:19.244229Z 0 [Note] mysqld: Shutdown complete
db_1    | 
db_1    | 2019-10-17 04:12:20+00:00 [Note] [Entrypoint]: Temporary server stopped
db_1    | 
db_1    | 2019-10-17 04:12:20+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
db_1    | 
db_1    | 2019-10-17T04:12:20.199594Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1    | 2019-10-17T04:12:20.200843Z 0 [Note] mysqld (mysqld 5.7.28) starting as process 1 ...
db_1    | 2019-10-17T04:12:20.204582Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1    | 2019-10-17T04:12:20.204632Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1    | 2019-10-17T04:12:20.204637Z 0 [Note] InnoDB: Uses event mutexes
db_1    | 2019-10-17T04:12:20.204640Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1    | 2019-10-17T04:12:20.204643Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1    | 2019-10-17T04:12:20.204645Z 0 [Note] InnoDB: Using Linux native AIO
db_1    | 2019-10-17T04:12:20.204935Z 0 [Note] InnoDB: Number of pools: 1
db_1    | 2019-10-17T04:12:20.205337Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1    | 2019-10-17T04:12:20.207192Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1    | 2019-10-17T04:12:20.216874Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1    | 2019-10-17T04:12:20.219008Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1    | 2019-10-17T04:12:20.232926Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1    | 2019-10-17T04:12:20.243650Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1    | 2019-10-17T04:12:20.243742Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1    | 2019-10-17T04:12:20.273068Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1    | 2019-10-17T04:12:20.273787Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1    | 2019-10-17T04:12:20.273823Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1    | 2019-10-17T04:12:20.274942Z 0 [Note] InnoDB: 5.7.28 started; log sequence number 12436822
db_1    | 2019-10-17T04:12:20.275285Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1    | 2019-10-17T04:12:20.275518Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1    | 2019-10-17T04:12:20.278721Z 0 [Note] InnoDB: Buffer pool(s) load completed at 191017  4:12:20
db_1    | 2019-10-17T04:12:20.280877Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1    | 2019-10-17T04:12:20.280914Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
db_1    | 2019-10-17T04:12:20.281538Z 0 [Warning] CA certificate ca.pem is self signed.
db_1    | 2019-10-17T04:12:20.281597Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
db_1    | 2019-10-17T04:12:20.281972Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1    | 2019-10-17T04:12:20.282028Z 0 [Note] IPv6 is available.
db_1    | 2019-10-17T04:12:20.282040Z 0 [Note]   - '::' resolves to '::';
db_1    | 2019-10-17T04:12:20.282052Z 0 [Note] Server socket created on IP: '::'.
db_1    | 2019-10-17T04:12:20.283613Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1    | 2019-10-17T04:12:20.290925Z 0 [Note] Event Scheduler: Loaded 0 events
db_1    | 2019-10-17T04:12:20.291302Z 0 [Note] mysqld: ready for connections.
db_1    | Version: '5.7.28'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
db_1    | 2019-10-17T04:12:40.385014Z 2 [Note] Access denied for user 'root'@'localhost' (using password: NO)
node_1  | module.js:472
node_1  |     throw err;
node_1  |     ^
node_1  | 
node_1  | Error: Cannot find module '/home/node/app/mobius'
node_1  |     at Function.Module._resolveFilename (module.js:470:15)
node_1  |     at Function.Module._load (module.js:418:25)
node_1  |     at Module.runMain (module.js:605:10)
node_1  |     at run (bootstrap_node.js:422:7)
node_1  |     at startup (bootstrap_node.js:143:9)
node_1  |     at bootstrap_node.js:537:3
mobius_docker_node_1 exited with code 1
db_1    | 2019-10-17T04:13:10.510295Z 3 [Note] Access denied for user 'root'@'localhost' (using password: NO)

**Comment by Cftn** [comment]
안녕하세요 전자부품연구원 안종관입니다. 
Docker 컴포즈 아래 Mobius 설정사항에서 "working_dir" 과 "volumes" 경로를 다운받으신 Mobius source 경로로 바꺼주셔야합니다. 

시도 후 연락 부탁드리겠습니다. 

Mobius

**working_dir: /home/node/app   # Sets the virtual image directory of the Nodejs-based Mobius.**

**volumes:                   # Import mobius source code from the host into the virtual image directory.
  - ./Mobius:/home/node/app**

**Comment by webos21** [comment]
넵, https://github.com/IoTKETI/Mobius.git 를 다운로드 받아 복사했더니 해당 이슈는 해결되었습니다.
