### ISSUE TITLE
docker-entrypoint-initdb.d is empty

### ISSUE THREAD

**Issue by hsebs** [IoTKETI/Mobius_Docker#4]
IoTKETI removed sql directory from Mobius but Mobius_Docker still uses it as docker-entrypoint-initdb.d.

**Comment by hsebs** [comment]
#3

**Comment by IoTKETI** [comment]
Hello, @hsebs 
The latest version of Mobius has deleted the folder containing the sql file. I temporarily modified the guide to the Mobius version URL where the sql file exists. I will update it after the internal meeting.
