### ISSUE TITLE
healthcheck command is wrong.

### ISSUE THREAD

**Issue by hsebs** [IoTKETI/Mobius_Docker#5]
Command should be include password.

![image](https://user-images.githubusercontent.com/19328795/73088861-6c7b3400-3f18-11ea-8b8b-1efc0511f355.png)

![image](https://user-images.githubusercontent.com/19328795/73088851-671de980-3f18-11ea-8954-8fcd909feabe.png)

**Comment by IoTKETI** [comment]
Hello, @hsebs 
I confirmed it. thank you for your contribution.
